### ISSUE TITLE
Doesn't work when JS is minified

### ISSUE THREAD

**Issue by nodeworks** [EfogDev/react-services-injector#2]
When I use webpack and minify the js files for production it doesn't work:

```
new webpack.optimize.UglifyJsPlugin({
        sourceMap: true,
        comments: false,
        compress: {
          warnings: false,
          screw_ie8: true,
          conditionals: true,
          unused: true,
          comparisons: true,
          sequences: true,
          dead_code: true,
          evaluate: true,
          if_return: true,
          join_vars: true,
        },
      })
```

I get: Unable to find service "MyService".

It works fine when the javascript is not minimized.

Version: 1.0.0-rc.3

**Comment by efogdev** [comment]
You're right, it's my fail. Will fix this ASAP.
Thanks for reporting the issue!

**Comment by nodeworks** [comment]
No problem! let me know when you push a revision, i'll check it out. Thanks!!

**Comment by efogdev** [comment]
1.0.0-rc.4 is available now.
Unfortunately, now you have to set `publicName` property in your services, but that's the only solution for minimization, I think.
Please, take a look on updated README.

**Comment by jasonjimnz** [comment]
@nodeworks did you used the react-script for making the build or you have used an specific version of Webpack ? I'm having the same issue and I have declared the publicName property.

I'm using 1.0.0-rc4 and I'm running the react-script build for making the production build

**Comment by efogdev** [comment]
@jasonjimnz is it possible to show me the code?

**Comment by esantanche** [comment]
It doesn't work when minified.

My code is here: https://github.com/esantanche/emsreact

I defined the publicName attributes of all services.

When minified, this.services is a mess. It doesn't contains the services. It contains 'this' (renamed 't') and, as a property, 'services'. This latter contains the services.

You may think that, when minified, a workaround would be to write 'this.services.t.services' instead of 'this.services'. But it doesn't work anyway.

I would love to find a solution instead of having to revert to Redux.

I'm working to disable minification, even though that's not optimal.

UPDATE: I can confirm that it works when I disable minification

**Comment by efogdev** [comment]
@esantanche Emanuele, thanks for reporting the issue!
You are totally right: there was a bug. I have fixed it and checked your project.
Now it works with minimization.
Please, upgrade to 1.0.0-rc.5

**Comment by esantanche** [comment]
Wonderful! It works! Thank you so much!

**Comment by efogdev** [comment]
Glad to help you :)
